routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

/*----------- 
|-Admin 
|------------*/
Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    Route::get('/',                         ['as' => 'index', 'uses' => 'IndexController@show']);
    Route::get('cities/{city}/businesses',  ['as' => 'cities.businesses', 'uses' => 'CityController@businesses']);
    Route::get('states/{state}/cities',     ['as' => 'states.cities', 'uses' => 'StateController@cities']);
    Route::get('states/{state}/businesses', ['as' => 'states.businesses', 'uses' => 'StateController@businesses']);

    Route::resource('businesses', 'BusinessController', ['except' => ['show']]);
    Route::resource('cities',     'CityController',     ['except' => ['show']]);
    Route::resource('locations',  'LocationController', ['except' => ['show']]);
    Route::resource('pages',      'PageController',     ['except' => ['show']]);
    Route::resource('states',     'StateController',    ['except' => ['show']]);
    Route::resource('users',      'UserController',     ['except' => ['show']]);
});


/*----------- 
|-Main 
|------------*/
Route::group(['namespace' => 'Main', 'as' => 'main.'], function () {


    Route::get('/', ['as' => 'index', 'uses'  => 'PageController@index']);

    Route::get('{state}/{city}/{business}/{location}', ['as' => 'locations.show', 'uses'  => 'LocationController@show']);
    Route::get('{state}/{city?}/{business?}/',         ['as' => 'locations.index', 'uses'  => 'LocationController@index']);



});

resources/views/admin/pages/_form.blade.php
<fieldset>
	{{ Form::label('slug', 'Slug') }}
	{{ Form::text('slug', null, ['required' => true]) }}
</fieldset>

<fieldset>
	{{ Form::label('title', 'Title') }}
	{{ Form::text('title', null, ['required' => true]) }}
</fieldset>

{{ Form::submit('Save') }}

resources/views/admin/pages/_table.blade.php
<table>
	<thead>
		<th>Title</th>
		<th></th>
	</thead>
	<tbody>
		@foreach ($pages as $page)
			<tr>
				<td>
					<a href="{{ route('admin.pages.edit', $page->id) }}">{{ $page->title }}</a><br>
					<span class="small"><a target="_blank" href="{{ url($page->slug) }}">{{ $page->slug }} <i class="fa fa-external-link"></i></a></span>
				</td>
				<td>
					<a target="_blank" href="{{ url($page->slug) }}">View <i class="fa fa-external-link"></i></a> |
					<a href="{{ route('admin.pages.edit', $page->id ) }}">Edit</a> | 
					<a class="delete-link" href="javascript:;">Delete</a>
					{{ Form::open(['method' => 'DELETE', 'route' => ['admin.pages.destroy', $page->id]]) }} {{ Form::close() }}
				</td>
			</tr>
		@endforeach
	</tbody>
</table>

resources/views/admin/pages/create.blade.php
@extends('admin.app', ['title' => 'Create a Page'])



@section('content')
	<h1><a href="{{ route('admin.pages.index') }}">Pages</a> / Create</h1>
	{{ Form::open(['route' => 'admin.pages.store', 'class' => 'validate']) }}
		@include('admin.pages._form')
	{{ Form::close() }}
@stop

resources/views/admin/pages/edit.blade.php
@extends('admin.app', ['title' => 'Edit Page: ' . $page->slug])



@section('content')
	<h1><a href="{{ route('admin.pages.index') }}">Pages</a> / Edit Page: <span data-mirror="slug">{{ $page->slug }}</span></h1>
	{{ Form::model($page, ['route' => ['admin.pages.update', $page->id], 'method' => 'PATCH', 'class' => 'validate']) }}
		@include('admin.pages._form')
	{{ Form::close() }}
@stop

resources/views/admin/pages/index.blade.php
@extends('admin.app', ['title' => 'Pages'])




@section('content')
	<a class="btn float-right" href="{{ route('admin.pages.create') }}">Create Page</a>
	<h1>Pages</h1>
	@include('admin.pages._table', ['pages' => $pages])
@stop