routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

/*----------- 
|-Admin 
|------------*/
Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    Route::get('/',                         ['as' => 'index', 'uses' => 'IndexController@show']);
    Route::get('cities/{city}/businesses',  ['as' => 'cities.businesses', 'uses' => 'CityController@businesses']);
    Route::get('states/{state}/cities',     ['as' => 'states.cities', 'uses' => 'StateController@cities']);
    Route::get('states/{state}/businesses', ['as' => 'states.businesses', 'uses' => 'StateController@businesses']);

    Route::resource('businesses', 'BusinessController', ['except' => ['show']]);
    Route::resource('cities',     'CityController',     ['except' => ['show']]);
    Route::resource('locations',  'LocationController', ['except' => ['show']]);
    Route::resource('pages',      'PageController',     ['except' => ['show']]);
    Route::resource('states',     'StateController',    ['except' => ['show']]);
    Route::resource('users',      'UserController',     ['except' => ['show']]);
});


/*----------- 
|-Main 
|------------*/
Route::group(['namespace' => 'Main', 'as' => 'main.'], function () {


    Route::get('/', ['as' => 'index', 'uses'  => 'PageController@index']);

    Route::get('{state}/{city}/{business}/{location}', ['as' => 'locations.show', 'uses'  => 'LocationController@show']);
    Route::get('{state}/{city?}/{business?}/',         ['as' => 'locations.index', 'uses'  => 'LocationController@index']);



});

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    protected $fillable = ['state_id', 'slug', 'name'];

    public function state() {
    	return $this->belongsTo('App\State');
    }

    public function businesses() {
    	return $this->hasMany('App\Business');
    }

    public static function lists() {
        return self::orderBy('name')->pluck('name', 'id')->all();
    }

    public function getLinkAttribute() {
        return url($this->state->slug . '/' . $this->slug);
    }
}

app/Http/Controllers/Main/LocationController.php
<?php

namespace App\Http\Controllers\Main;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Location;
use App\Business;
use App\City;
use App\State;
use App\Page;

class LocationController extends Controller
{
    public function index($state_slug, $city_slug = null, $business_slug = null, Request $request) {

    	// Check if there's a page we should be showing:
    	//////////////
    	$page = Page::where('slug', $request->path())->first();
    	if ($page) {
    		return view('main.page', compact('page'));
    	}


    	// Else - list the locations for this combination.
    	//////////////

    	$state     = State::where('slug', $state_slug)->first();
    	$city      = $state ? City::where('slug', $city_slug)->where('state_id', $state->id)->first() : null;
    	$business  = $city ? Business::where('slug', $business_slug)->where('city_id', $city->id)->first() : null;

    	$query = Location::with('business.city.state');
    	$query->parents($state, $city, $business);
    	$locations = $query->paginate(20);

    	return view('main.locations.index', compact('locations', 'business', 'city', 'state'));
    }

    public function show($state_slug, $city_slug, $business_slug, $location_slug) {


        $state     = State::where('slug', $state_slug)->firstOrFail();
        $city      = City::where('slug', $city_slug)->where('state_id', $state->id)->firstOrFail();
        $business  = Business::where('slug', $business_slug)->where('city_id', $city->id)->firstOrFail();


        $location  = Location::where('slug', $location_slug)->where('business_id', $business->id)->firstOrFail();

        $location->load('business.city.state');

        return view('main.locations.show', compact('location', 'business', 'city', 'state'));

    }
}

app/Http/Controllers/Main/PageController.php
<?php

namespace App\Http\Controllers\Main;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Location;

class PageController extends Controller
{
	public function index() {

		$query = Location::with('business.city.state');
    	$locations = $query->paginate(20);

    	return view('main.index', compact('locations'));
    }


    
    
}

resources/views/main/partials/adsense.blade.php
<div class="external">Adsense</div>

resources/views/main/partials/breadcrumbs.blade.php
<div class="breadcrumbs">
	<div class="c">
		<ul>
			<li><a href="{{ url('/') }}"><i class="fa fa-home"></i> Home</a></li>
			@if (isset($state))
				<li><a href="{{ $state->link }}">{{ $state->name }}</a></li>
				@if (isset($city))
					<li><a href="{{ $city->link }}">{{ $city->name }}</a></li>
					@if (isset($business))
						<li><a href="{{ $business->link }}">{{ $business->name }}</a></li>
						@if (isset($location))
							<li><a href="{{ $location->link }}">{{ $location->address }}</a></li>
						@endif
					@endif
				@endif
			@elseif (isset($page))
				<li><a href="{{ $page->link }}">{{ $page->title }}</a></li>
			@endif
		</ul>
	</div><!-- c -->
</div><!-- breadcrumbs -->

resources/views/main/partials/map-single.blade.php
<iframe class="map" src="https://www.google.com/maps/embed/v1/view?key=AIzaSyBs80mQSfGpwGbhFrBh5OxqNlc0tvWUG6g&center={{ $location->lat }},{{ $location->lng }}&zoom=14"></iframe>

resources/views/main/partials/map.blade.php
@if (isset($locations) && count($locations) > 0)
  <div class="map"><div id="map"></div></div>
  <script>
  	function initMap() {
      var map = new google.maps.Map(document.getElementById('map'), {
        	zoom: 5,
        	center: {lat: {{ $locations[0]->lat }} , lng: {{ $locations[0]->lng }} }
      });
      var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    	var markers = locations.map(function(location, i) {
      		return new google.maps.Marker({
        		position: location,
        		label: labels[i % labels.length]
      		});
    	});
    	var markerCluster = new MarkerClusterer(map, markers, {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});
  	}

  	var locations = [
  		@foreach ($locations as $location)
  			{lat: {{ $location->lat }}, lng: {{ $location->lng }} },
  		@endforeach
  	]
  </script>
  <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAs03aWH-P2ih7cDBWQIoP213kyKB85Jes&callback=initMap"></script>
@endif